version: "3"

services: 
  discord-bot-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/discord-bot

  discord-bot-prod:
    build: 
      context: .
      dockerfile: Dockerfile.prod